name: libra_read
description: Read Log App.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # chart
  fl_chart: ^0.63.0
  provider: ^6.0.0
  # font
  google_fonts: ^5.1.0
  # drift関連
  drift: ^2.11.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.5
  path: ^1.8.3
  # API
  http: ^1.1.0
  # string format
  sprintf: ^6.0.0
  # バーコードスキャナ
  barcode_scan2: any
  # ファイルアップローダ
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  drift_dev: ^2.11.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/no_image.jpg
    - assets/images/stack_books.png
